# Generated by Django 3.2.1 on 2021-06-08 22:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_equipement', models.CharField(max_length=50, unique=True)),
                ('serie_equipement', models.CharField(blank=True, max_length=30)),
                ('emplacement_equipement', models.CharField(blank=True, max_length=50)),
                ('designation_equipement', models.CharField(blank=True, max_length=500)),
                ('client_equipement', models.CharField(blank=True, max_length=150)),
                ('date_debut_fonctionnement_equipement', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipements',
            },
        ),
        migrations.CreateModel(
            name='Pdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_pdr', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('designation_pdr', models.CharField(blank=True, max_length=200)),
                ('categorie_pdr', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite_pdr', models.IntegerField(blank=True, null=True)),
                ('min_pdr', models.IntegerField(blank=True, null=True)),
                ('prix_pdr', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('emplacement_pdr', models.CharField(blank=True, max_length=100)),
                ('fournisseur_pdr', models.CharField(blank=True, max_length=200)),
                ('contact_fournisseur_pdr', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'Pdrs',
            },
        ),
        migrations.CreateModel(
            name='Type_equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'type_equipements',
            },
        ),
        migrations.CreateModel(
            name='PlanPreventive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalle_maintenance', models.CharField(blank=True, max_length=50, null=True)),
                ('semaine_maintenance', models.CharField(blank=True, max_length=50, null=True)),
                ('premiere_mois_maintenance', models.CharField(blank=True, max_length=30, null=True)),
                ('cell_position', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None), blank=True, null=True, size=None)),
                ('eq_inter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoApp.equipement')),
                ('type_eq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoApp.type_equipement')),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(blank=True, choices=[('P', 'Préventive'), ('C', 'Corrective')], max_length=1, null=True)),
                ('date_declaration_defaillance', models.DateTimeField(blank=True, null=True)),
                ('date_intervention', models.DateField(blank=True, null=True)),
                ('debut_intervention', models.TimeField(blank=True, null=True)),
                ('fin_intervention', models.TimeField(blank=True, null=True)),
                ('duree_intervention', models.IntegerField(blank=True, null=True)),
                ('declare_par_defaillance', models.CharField(blank=True, max_length=100, null=True)),
                ('cause_intervention', models.CharField(blank=True, max_length=500, null=True)),
                ('actions_intervention', models.CharField(blank=True, max_length=400, null=True)),
                ('pieces_utilisees', models.CharField(blank=True, max_length=500, null=True)),
                ('observation_intervention', models.CharField(blank=True, max_length=500, null=True)),
                ('resultat_intervention', models.CharField(blank=True, max_length=100, null=True)),
                ('eq_inter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoApp.equipement')),
                ('type_inter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoApp.type_equipement')),
            ],
            options={
                'db_table': 'interventions',
            },
        ),
        migrations.AddField(
            model_name='equipement',
            name='type_equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoApp.type_equipement'),
        ),
    ]
