# Generated by Django 3.2.1 on 2021-06-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpreventive',
            name='etat_planning',
            field=models.CharField(blank=True, choices=[('P', 'Planifié'), ('R', 'Réalisé')], max_length=1, null=True),
        ),
    ]
