# Generated by Django 3.2.1 on 2021-06-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoApp', '0003_auto_20210609_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='client_equipement',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='designation_equipement',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='emplacement_equipement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='serie_equipement',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='pieces_utilisees',
            field=models.ManyToManyField(blank=True, to='gmaoApp.Pdr'),
        ),
        migrations.AlterField(
            model_name='pdr',
            name='prix_pdr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
